"""Locust load tests for DeployHub.

Examples:
    locust -f tests/load/locustfile.py --headless -u 50 -r 10 -t 2m
    locust -f tests/load/locustfile.py --headless -u 200 -r 20 -t 5m WebhookStormUser
    locust -f tests/load/locustfile.py   # open the web UI

Override service bases with AUTH_URL / PROJECT_URL / DEPLOYMENT_URL / FRONTEND_URL.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import sys
import uuid
from pathlib import Path

from locust import HttpUser, between, constant, events, tag, task

# Reuse the shared test helpers so this reads the *real* keypair/secrets
# generated by scripts/generate_secrets.py when the live stack was started
# with them (falling back to a throwaway keypair otherwise).
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from tests.helpers.settings import JWT_ALGORITHM, JWT_PRIVATE_KEY, WEBHOOK_SECRET  # noqa: E402

AUTH_URL = os.getenv("AUTH_URL", "http://127.0.0.1:8001")
PROJECT_URL = os.getenv("PROJECT_URL", "http://127.0.0.1:8002")
BUILD_URL = os.getenv("BUILD_URL", "http://127.0.0.1:8004")
UPLOAD_URL = os.getenv("UPLOAD_URL", "http://127.0.0.1:8005")
DEPLOYMENT_URL = os.getenv("DEPLOYMENT_URL", "http://127.0.0.1:8006")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://127.0.0.1:3000")


def _jwt() -> str:
    import jwt
    from datetime import datetime, timedelta, timezone

    return jwt.encode(
        {
            "sub": "00000000-0000-0000-0000-000000000001",
            "exp": datetime.now(timezone.utc) + timedelta(minutes=30),
        },
        JWT_PRIVATE_KEY,
        algorithm=JWT_ALGORITHM,
    )


def _sign(body: bytes) -> str:
    digest = hmac.new(WEBHOOK_SECRET.encode("utf-8"), msg=body, digestmod=hashlib.sha256).hexdigest()
    return f"sha256={digest}"


class HealthProbeUser(HttpUser):
    """Saturate liveness probes across every microservice."""

    wait_time = constant(0.05)
    weight = 3
    host = AUTH_URL

    @tag("health")
    @task(5)
    def auth_health(self):
        self.client.get(f"{AUTH_URL}/health", name="health:auth")

    @tag("health")
    @task(5)
    def project_health(self):
        self.client.get(f"{PROJECT_URL}/health", name="health:project")

    @tag("health")
    @task(3)
    def build_health(self):
        self.client.get(f"{BUILD_URL}/health", name="health:build")

    @tag("health")
    @task(3)
    def upload_health(self):
        self.client.get(f"{UPLOAD_URL}/health", name="health:upload")

    @tag("health")
    @task(3)
    def deployment_health(self):
        self.client.get(f"{DEPLOYMENT_URL}/health", name="health:deployment")

    @tag("health")
    @task(1)
    def auth_ready(self):
        self.client.get(f"{AUTH_URL}/ready", name="ready:auth")


class ProjectApiUser(HttpUser):
    """Authenticated project list/create/get mix."""

    wait_time = between(0.2, 1.0)
    weight = 4
    host = PROJECT_URL

    def on_start(self):
        self.headers = {"Authorization": f"Bearer {_jwt()}"}
        self.project_ids = []

    @tag("api")
    @task(10)
    def list_projects(self):
        self.client.get("/projects/", headers=self.headers, name="projects:list")

    @tag("api")
    @task(2)
    def create_project(self):
        suffix = uuid.uuid4().hex[:10]
        with self.client.post(
            "/projects/",
            headers=self.headers,
            json={"repo_name": f"load-{suffix}", "repo_url": f"https://github.com/load/{suffix}"},
            name="projects:create",
            catch_response=True,
        ) as response:
            if response.status_code == 201:
                self.project_ids.append(response.json()["id"])
                response.success()
            elif response.status_code in {400, 401, 409}:
                response.success()
            else:
                response.failure(f"unexpected {response.status_code}")

    @tag("api")
    @task(4)
    def get_project(self):
        if not self.project_ids:
            self.list_projects()
            return
        pid = self.project_ids[-1]
        self.client.get(f"/projects/{pid}", headers=self.headers, name="projects:get")


class WebhookStormUser(HttpUser):
    """High-rate signed webhook deliveries (unique delivery ids)."""

    wait_time = between(0.05, 0.2)
    weight = 5
    host = PROJECT_URL

    def on_start(self):
        self.project_id = str(uuid.uuid4())

    @tag("webhook")
    @task
    def simulate_webhook_push(self):
        payload = {
            "ref": "refs/heads/main",
            "after": uuid.uuid4().hex + uuid.uuid4().hex[:8],
            "repository": {"clone_url": "https://github.com/test/repo"},
        }
        body = json.dumps(payload, separators=(",", ":")).encode("utf-8")
        headers = {
            "Content-Type": "application/json",
            "X-Hub-Signature-256": _sign(body),
            "X-GitHub-Delivery": str(uuid.uuid4()),
            "X-GitHub-Event": "push",
        }
        with self.client.post(
            f"/webhooks/github/{self.project_id}",
            data=body,
            headers=headers,
            name="webhooks:push",
            catch_response=True,
        ) as response:
            if response.status_code in {200, 400, 404}:
                response.success()
            else:
                response.failure(f"unexpected {response.status_code}")


class DeploymentReadUser(HttpUser):
    wait_time = between(0.2, 0.8)
    weight = 2
    host = DEPLOYMENT_URL

    @tag("api")
    @task(8)
    def list_for_random_project(self):
        pid = str(uuid.uuid4())
        self.client.get(f"/deployments/{pid}", name="deployments:list")

    @tag("api")
    @task(2)
    def missing_detail(self):
        self.client.get(f"/deployments/detail/{uuid.uuid4()}", name="deployments:detail")


class FrontendBrowseUser(HttpUser):
    wait_time = between(0.5, 2.0)
    weight = 2
    host = FRONTEND_URL

    @tag("frontend")
    @task(5)
    def home(self):
        self.client.get("/", name="fe:home")

    @tag("frontend")
    @task(2)
    def login(self):
        self.client.get("/login", name="fe:login")

    @tag("frontend")
    @task(1)
    def docs(self):
        self.client.get("/docs", name="fe:docs")

    @tag("frontend")
    @task(1)
    def dashboard(self):
        self.client.get("/dashboard", name="fe:dashboard")


class UnauthenticatedFloodUser(HttpUser):
    """Confirm protected routes stay rejected under load."""

    wait_time = constant(0.1)
    weight = 2
    host = PROJECT_URL

    @tag("security")
    @task
    def list_without_token(self):
        with self.client.get("/projects/", name="projects:unauth", catch_response=True) as response:
            if response.status_code in {401, 403}:
                response.success()
            else:
                response.failure(f"expected 401/403, got {response.status_code}")


class ConcurrentRaceUser(HttpUser):
    """Zero-wait bursts that hammer the same resources (locks, duplicates, lists)."""

    wait_time = constant(0)
    weight = 3
    host = PROJECT_URL

    def on_start(self):
        self.headers = {"Authorization": f"Bearer {_jwt()}"}
        self.delivery_id = str(uuid.uuid4())
        self.project_id = str(uuid.uuid4())
        self.repo_name = f"locust-{uuid.uuid4().hex[:8]}"

    @tag("concurrency")
    @task(4)
    def duplicate_create(self):
        with self.client.post(
            "/projects/",
            headers=self.headers,
            json={
                "repo_name": self.repo_name,
                "repo_url": f"https://github.com/locust/{self.repo_name}",
            },
            name="concurrency:duplicate-create",
            catch_response=True,
        ) as response:
            if response.status_code in {201, 400, 401, 409, 422}:
                response.success()
            else:
                response.failure(f"unexpected {response.status_code}")

    @tag("concurrency")
    @task(6)
    def same_delivery_webhook(self):
        payload = {
            "ref": "refs/heads/main",
            "after": "a" * 40,
            "repository": {"clone_url": "https://github.com/test/repo"},
        }
        body = json.dumps(payload, separators=(",", ":")).encode("utf-8")
        headers = {
            "Content-Type": "application/json",
            "X-Hub-Signature-256": _sign(body),
            "X-GitHub-Delivery": self.delivery_id,
            "X-GitHub-Event": "push",
        }
        with self.client.post(
            f"/webhooks/github/{self.project_id}",
            data=body,
            headers=headers,
            name="concurrency:same-delivery",
            catch_response=True,
        ) as response:
            if response.status_code in {200, 400, 404}:
                response.success()
            else:
                response.failure(f"unexpected {response.status_code}")

    @tag("concurrency")
    @task(5)
    def parallel_list(self):
        self.client.get("/projects/", headers=self.headers, name="concurrency:list")


@events.test_start.add_listener
def _on_start(environment, **_kwargs):
    environment.runner.logger.info(
        "DeployHub load test targeting auth=%s project=%s deployment=%s",
        AUTH_URL,
        PROJECT_URL,
        DEPLOYMENT_URL,
    )
